<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Devlooped.WhatsApp.CodeAnalysis</AssemblyName>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackFolder>analyzers/dotnet/cs</PackFolder>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\WhatsApp\IWhatsAppClient.cs" Link="IWhatsAppClient.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NuGetizer" Version="1.4.9" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" Pack="false" />
    <PackageReference Include="PolySharp" Version="1.16.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
