<Project Sdk="Microsoft.NET.Sdk"> 

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <AssemblyName>Devlooped.WhatsApp</AssemblyName>
    <Description>WhatsApp agents for Azure Functions</Description>
    <PackageId>Devlooped.WhatsApp</PackageId>
    <PackContent>false</PackContent>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.5.2" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" Version="9.6.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.10.0" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.6" />

    <PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
    <PackageReference Include="Devlooped.JQ" Version="1.7.1.8" PackExclude="contentFiles" />
    <PackageReference Include="Devlooped.TableStorage" Version="5.4.0" />

    <PackageReference Include="NuGetizer" Version="1.2.4" />
    <PackageReference Include="PolySharp" Version="1.15.0" />
    <PackageReference Include="System.Linq.Async" Version="6.0.3" />
    <PackageReference Include="ThisAssembly.AssemblyInfo" Version="2.0.14" PrivateAssets="all" />
    <PackageReference Include="Ulid " Version="1.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeAnalysis\CodeAnalysis.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tests" />
  </ItemGroup>

</Project>
