# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: sample

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  sample:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4

      - name: ⚙ dotnet
        uses: devlooped/actions-dotnet-env@v1

      - name: 📦 publish
        working-directory: src/SampleApp/Sample
        run: |
          dotnet restore
          dotnet publish -c Release -o ./publish
          chmod 755 ./publish/lib/jq-linux-amd64

      - name: 🗜️ flex zip
        working-directory: src/SampleApp/Sample/publish
        run: |
          zip -r "$GITHUB_WORKSPACE/released-package.zip" .

      - name: 🔓 login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3A2F16E6509A4F298C80F59E1941F771 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_08449B8A3C6E4F18B37203B67E099362 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F97F119894404180A100F53C19B8D1B7 }}

      - name: 🚀 deploy
        run: |
            az functionapp deployment source config-zip \
                --name devlooped-whatsapp \
                --resource-group oss \
                --src "$GITHUB_WORKSPACE/released-package.zip"